#import "../index.typ": template, tufted
#show: template.with(title: "Research")

#tufted.margin-note[
  #link("https://scholar.google.com/citations?user=2VhvrAIAAAAJ")[Google Scholar] \
  \
  #text(size: 0.85em, fill: gray)[_Auto-generated by Claude\ (July 2026)_]
]

= Research

My recent work focuses on electronic crystal phases and topological order in moiré and rhombohedral graphene multilayers, and on how phonons mediate interactions between chiral edge modes in anomalous Hall crystals. I study emergent phenomena such as charge ordering, electron-phonon coupling, and topological Hall effects in graphene multilayers and twisted heterostructures, combining analytical theory with numerical methods.

== Publications

=== 2026

- *#link("https://arxiv.org/abs/2607.10320")[Retarded interaction between opposite chiral edges in anomalous Hall crystals]* \
  #text(size: 0.85em)[*Wangqian Miao*, Mu-Yang Chen, Binghai Yan, Chunli Huang \ _arXiv_ 2607.10320 (2026)]

- *#link("https://arxiv.org/abs/2512.23082")[Various electronic crystal phases in rhombohedral graphene multilayers]* \
  #text(size: 0.85em)[*Wangqian Miao*, Chu Li \ _Phys. Rev. B_ *113*, 155136 (2026)]

- *#link("https://doi.org/10.1016/j.newton.2026.100638")[Emergence of topological electron crystals in bilayer graphene-Mott insulator heterostructures]* \
  #text(size: 0.85em)[*Wangqian Miao*, Tianyu Qiao, Xue-Yang Song, Yinghai Xu, Yiwei Chen, Lei Wang, Xi Dai \ _Newton_ *2*, 100638 (2026)]

=== 2025

- *#link("https://doi.org/10.1103/PhysRevB.111.195136")[Zeroth Landau level crossings in two-dimensional topological insulators]* \
  #text(size: 0.85em)[Boliang Liu, *Wangqian Miao*, Simon Munyan, Susanne Stemmer, Xi Dai \ _Phys. Rev. B_ *111*, 195136 (2025)]

- *#link("https://doi.org/10.1103/PhysRevB.111.155126")[Moiré optical phonons coupled to heavy electrons in magic-angle twisted bilayer graphene]* \
  #text(size: 0.85em)[Hao Shi, *Wangqian Miao*, Xi Dai \ _Phys. Rev. B_ *111*, 155126 (2025)]

- *#link("https://doi.org/10.1103/PhysRevB.111.045113")[Artificial moiré engineering for an ideal Bernevig-Hughes-Zhang model]* \
  #text(size: 0.85em)[*Wangqian Miao*, Arman Rashidi, Xi Dai \ _Phys. Rev. B_ *111*, 045113 (2025)]

=== 2024

- *#link("https://doi.org/10.1038/s41586-024-08818-5")[Strong electron–phonon coupling in magic-angle twisted bilayer graphene]* \
  #text(size: 0.85em)[Cheng Chen, Kevin P. Nuckolls, Shuhan Ding, *Wangqian Miao*, Dillon Wong, et al. \ _Nature_ *636*, 342–347 (2024)]

- *#link("https://arxiv.org/abs/2411.08108")[Universal moiré-model-building method without fitting: application to twisted MoTe#sub[2] and WSe#sub[2]]* \
  #text(size: 0.85em)[Yan Zhang, Hanqi Pi, Jiaxuan Liu, *Wangqian Miao*, Ziyue Qi, Nicolas Regnault, Hongming Weng, Xi Dai, B. Andrei Bernevig, Quansheng Wu, et al. \ _arXiv_ 2411.08108 (2024)]

- *#link("https://doi.org/10.1103/PhysRevB.109.155408")[Engineering the in-plane anomalous Hall effect in Cd#sub[3]As#sub[2] thin films]* \
  #text(size: 0.85em)[*Wangqian Miao*, Binghao Guo, Susanne Stemmer, Xi Dai \ _Phys. Rev. B_ *109*, 155408 (2024)]

=== 2023

- *#link("https://doi.org/10.1103/PhysRevB.107.125112")[Truncated atomic plane wave method for subband structure calculations of moiré systems]* \
  #text(size: 0.85em)[*Wangqian Miao*, Chu Li, Xu Han, Ding Pan, Xi Dai \ _Phys. Rev. B_ *107*, 125112 (2023)]

- *#link("https://doi.org/10.1103/PhysRevLett.131.046601")[Zeeman field-induced two-dimensional Weyl semimetal phase in cadmium arsenide]* \
  #text(size: 0.85em)[Binghao Guo, *Wangqian Miao*, Victor Huang, Alexander C. Lygo, Xi Dai, Susanne Stemmer \ _Phys. Rev. Lett._ *131*, 046601 (2023)]
