#import "../index.typ": template, tufted
#show: template.with(title: "Research")

#tufted.margin-note[
  #link("https://scholar.google.com/citations?user=2VhvrAIAAAAJ")[Google Scholar] \
  \
  #text(size: 0.85em, fill: gray)[_Auto-generated by Claude\ (June 2026)_]
]

= Research

My research is in theoretical condensed matter physics. I study novel quantum phases of matter in low-dimensional systems, with an emphasis on the interplay of topology, electron correlation, and lattice geometry. My approach combines analytical theory with numerical computation.

== Current Focus

As a Postdoctoral Fellow at Penn State working with Prof. #link("https://sites.psu.edu/byan/")[Binghai Yan] and Prof. #link("https://sites.psu.edu/chaoxingliu/")[Chaoxing Liu], my recent work centers on:

- *Electron crystals* — Charge ordering and crystallization in graphene multilayers and heterostructures, including topological crystal phases with quantized anomalous Hall effects in triangular, honeycomb, and kagome charge orders.

- *Quantum capacitors* — Exploring coherence-based quantum energy storage rooted in band topology.

- *Moiré materials* — Theoretical modeling and engineering of twisted and patterned 2D material systems, developing efficient numerical methods and building minimal models for novel moiré platforms.

- *Correlated phenomena in 2D* — Emergent phases in strongly interacting electron systems, including Mott physics, heavy-electron behavior, and exotic superconductivity.

== Publications

=== 2025

- *#link("https://arxiv.org/abs/2512.23082")[Various electronic crystal phases in rhombohedral graphene multilayers]* \
  #text(size: 0.85em)[*Wangqian Miao*, Chu Li \ _arXiv_ 2512.23082 (2025)]

- *#link("https://arxiv.org/abs/2512.23084")[Emergence of Topological Electronic Crystals in Bilayer Graphene–Mott Insulator Heterostructures]* \
  #text(size: 0.85em)[*Wangqian Miao*, Tianyu Qiao, Xue-Yang Song, Xi Dai \ _arXiv_ 2512.23084 (2025)]

- *#link("https://doi.org/10.1103/PhysRevB.111.195136")[Zeroth Landau level crossings in two-dimensional topological insulators]* \
  #text(size: 0.85em)[Boliang Liu, *Wangqian Miao*, Simon Munyan, Susanne Stemmer, Xi Dai \ _Phys. Rev. B_ *111*, 195136 (2025)]

- *#link("https://doi.org/10.1103/PhysRevB.111.155126")[Moiré optical phonons coupled to heavy electrons in magic-angle twisted bilayer graphene]* \
  #text(size: 0.85em)[Hao Shi, *Wangqian Miao*, Xi Dai \ _Phys. Rev. B_ *111*, 155126 (2025)]

- *#link("https://doi.org/10.1103/PhysRevB.111.045113")[Artificial moiré engineering for an ideal Bernevig-Hughes-Zhang model]* \
  #text(size: 0.85em)[*Wangqian Miao*, Arman Rashidi, Xi Dai \ _Phys. Rev. B_ *111*, 045113 (2025)]

=== 2024

- *#link("https://doi.org/10.1038/s41586-024-08818-5")[Strong electron–phonon coupling in magic-angle twisted bilayer graphene]* \
  #text(size: 0.85em)[Cheng Chen, Kevin P. Nuckolls, Shuhan Ding, *Wangqian Miao*, Dillon Wong, et al. \ _Nature_ *636*, 342–347 (2024)]

- *#link("https://arxiv.org/abs/2411.08108")[Universal moiré-model-building method without fitting: application to twisted MoTe#sub[2] and WSe#sub[2]]* \
  #text(size: 0.85em)[Yan Zhang, Hanqi Pi, Jiaxuan Liu, *Wangqian Miao*, Ziyue Qi, Nicolas Regnault, Hongming Weng, Xi Dai, B. Andrei Bernevig, Quansheng Wu, et al. \ _arXiv_ 2411.08108 (2024)]

- *#link("https://doi.org/10.1103/PhysRevB.109.155408")[Engineering the in-plane anomalous Hall effect in Cd#sub[3]As#sub[2] thin films]* \
  #text(size: 0.85em)[*Wangqian Miao*, Binghao Guo, Susanne Stemmer, Xi Dai \ _Phys. Rev. B_ *109*, 155408 (2024)]

=== 2023

- *#link("https://doi.org/10.1103/PhysRevB.107.125112")[Truncated atomic plane wave method for subband structure calculations of moiré systems]* \
  #text(size: 0.85em)[*Wangqian Miao*, Chu Li, Xu Han, Ding Pan, Xi Dai \ _Phys. Rev. B_ *107*, 125112 (2023)]

- *#link("https://doi.org/10.1103/PhysRevLett.131.046601")[Zeeman field-induced two-dimensional Weyl semimetal phase in cadmium arsenide]* \
  #text(size: 0.85em)[Binghao Guo, *Wangqian Miao*, Victor Huang, Alexander C. Lygo, Xi Dai, Susanne Stemmer \ _Phys. Rev. Lett._ *131*, 046601 (2023)]
